### PR TITLE
bump client to CC 238

### PR DESCRIPTION
**Pull request by carabasdaniel**

### CODE REVIEW

**Comment by carabasdaniel** [comment]
verify this please

**Comment by JohannesRudolph** [comment]
@carabasdaniel how did you generate the API implementation? I can't seem to find the generator scripts in this repository, your help would be appreciated.

**Comment by mihaibuzgau** [comment]
Hi @JohannesRudolph, thank you for your interest on this project, the tool that generates the API implementation is not open-source, yet.

**Comment by carabasdaniel** [comment]
verify this please

**Comment by carabasdaniel** [comment]
verify this please

**Comment by carabasdaniel** [comment]
verify this please

**Comment by mihaibuzgau** [comment]
LGTM

**Pull request merged**
